
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: spireentries.spiffeid.io.spiffe
spec:
  group: spiffeid.io.spiffe
  names:
    kind: SpireEntry
    listKind: SpireEntryList
    plural: spireentries
    singular: spireentry
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: SpireEntry is the Schema for the spireentries API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SpireEntrySpec defines the desired state of SpireEntry
          properties:
            selector:
              properties:
                arbitrary:
                  items:
                    type: string
                  type: array
                namespace:
                  type: string
                podLabel:
                  additionalProperties:
                    type: string
                  description: Pod label names/values to match for this spiffe ID
                    To match, pods must be in the same namespace as this ID resource.
                  type: object
                podName:
                  type: string
                serviceAccount:
                  type: string
              type: object
            spiffeId:
              type: string
          required:
          - selector
          - spiffeId
          type: object
        status:
          description: SpireEntryStatus defines the observed state of SpireEntry
          properties:
            entryId:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
