
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.4
  creationTimestamp: null
  name: clusterspiffeids.spiffeid.spiffe.io
spec:
  group: spiffeid.spiffe.io
  names:
    kind: ClusterSpiffeID
    listKind: ClusterSpiffeIDList
    plural: clusterspiffeids
    singular: clusterspiffeid
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterSpiffeID is the Schema for the clusterspiffeids API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterSpiffeIDSpec defines the desired state of ClusterSpiffeID
          properties:
            selector:
              properties:
                arbitrary:
                  description: Arbitrary k8s selectors
                  items:
                    type: string
                  type: array
                containerImage:
                  description: ContainerImage to match
                  type: string
                containerName:
                  description: ContainerName to match
                  type: string
                namespace:
                  description: Namespace to match for this spiffe ID
                  type: string
                podLabel:
                  additionalProperties:
                    type: string
                  description: Pod label names/values to match for this spiffe ID
                  type: object
                podName:
                  description: Pod names to match for this spiffe ID
                  type: string
                podUid:
                  description: Pod UIDs to match for this spiffe ID
                  type: string
                serviceAccount:
                  description: ServiceAccount to match for this spiffe ID
                  type: string
              type: object
            spiffeId:
              type: string
          required:
          - selector
          - spiffeId
          type: object
        status:
          description: ClusterSpiffeIDStatus defines the observed state of ClusterSpiffeID
          properties:
            entryId:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
